# Generated by Django 3.2 on 2021-05-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=64)),
                ('income', models.IntegerField()),
                ('expertise', models.CharField(max_length=256)),
                ('division', models.CharField(max_length=256)),
                ('hours', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=64)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='main.profile')),
                ('rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep', to='main.profile')),
            ],
        ),
    ]
