# Generated by Django 3.2 on 2021-05-08 21:28

from django.db import migrations, models
import django.db.models.deletion


def initialize(apps, schema_editor):
    Client = apps.get_model('main', 'Client')
    Rep = apps.get_model('main', 'Rep')
    for i in range(1, 6):
        c = Client(username=f"Client {i}", name=f"Client {i}", age=18, address="123 Avenue", gender="M", income=0)
        r = Rep(username=f"Rep {i}", name=f"Rep {i}", age=18, address="123 Avenue", gender="M", expertise="AUTO", division="None", hours="8")
        c.save()
        r.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.profile')),
                ('income', models.IntegerField()),
            ],
            bases=('main.profile',),
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.profile')),
                ('expertise', models.CharField(max_length=256)),
                ('division', models.CharField(max_length=256)),
                ('hours', models.CharField(max_length=256)),
            ],
            bases=('main.profile',),
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=64)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='main.client')),
                ('rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep', to='main.rep')),
            ],
        ),
        migrations.RunPython(initialize),
    ]